
services:
  backend:
    build:
      context: ./Backend
    container_name: backend
    ports:
      - "5001:5000"
    env_file:
      - ./Backend/.env
    working_dir: /app
    command: ["npm", "start"]
    

  frontend:
    build:
      context: ./Frontend
    container_name: frontend
    ports:
      - "5173:5173"
    env_file:
      - ./Frontend/.env
    working_dir: /app
    command: ["npm", "run", "dev"]
    